In [1]:
import pandas as pd
from sqlalchemy import MetaData, select
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session, registry
from NextVisionML.util import get_engine
from NextVisionML import MLContext

engine = get_engine()
metadata = MetaData()
metadata.reflect(bind=engine)
Base = automap_base(metadata=metadata)
Base.prepare(autoload_with=engine)    
mapper_registry = registry()
con = engine.connect()

In [2]:

datapoint = pd.read_sql_table("datapoint", con)
#labels = pd.read_sql_table("label", con)
#label_values = pd.read_sql_table("label_categorical", con)
datapoint_label_values = pd.read_sql_table("datapoint_class_label", con)
features = pd.read_sql_table("feature", con)
datapoint_features = pd.read_sql_table("datapoint_feature_value", con)
datapoint = datapoint.rename(columns={'id': "datapoint_id"})

In [3]:
datapoint

        datapoint_id  datapoint_mappings_id            datetime
0                  1                      1 2016-01-01 00:00:00
1                  2                      1 2016-01-01 00:00:00
2                  3                      1 2016-01-01 00:00:00
3                  4                      1 2016-01-01 00:00:00
4                  5                      1 2016-01-01 00:10:00
...              ...                    ...                 ...
417136       1105130                      2 2017-12-31 23:40:00
417137       1105131                      2 2017-12-31 23:50:00
417138       1105132                      2 2017-12-31 23:50:00
417139       1105133                      2 2017-12-31 23:50:00
417140       1105134                      2 2017-12-31 23:50:00

[417141 rows x 3 columns]

In [4]:
for i, row in features.iterrows():
    feature_id = row["id"]
    feature_df = datapoint_features[datapoint_features["feature_id"]==feature_id]
    feature_df = feature_df.drop(columns={"id", "feature_id"})
    datapoint = pd.merge(datapoint, feature_df, on='datapoint_id')
    datapoint.rename(columns={'value': row["name"]}, inplace=True)
    if "datapoint_id" in datapoint.columns:
        pass
        #datapoint = datapoint.drop(columns={"datapoint_id"})
    if "id_x" in datapoint.columns:
        datapoint = datapoint.drop(columns={"id_x"})
    if "id_y" in datapoint.columns:
        datapoint = datapoint.drop(columns={"id_y"})

In [5]:
datapoint = pd.merge(datapoint, datapoint_label_values, on='datapoint_id')

In [7]:
datapoint

,datapoint_id,datapoint_mappings_id,datetime,Gen_RPM_Max,Gen_RPM_Min,Gen_RPM_Avg,Gen_RPM_Std,Gen_Bear_Temp_Avg,Gen_Phase1_Temp_Avg,Gen_Phase2_Temp_Avg,...,Anemometer2_Offset,Anemometer2_CorrGain,Anemometer2_CorrOffset,DistanceAirPress,AirRessureSensorZeroOffset,Anemometer1_Avg_Freq,Anemometer2_Avg_Freq,Pressure_Avg_Freq,id,label_categorical_id
0,1,1,2016-01-01 00:00:00,1270.0,1232.8,1248.5,6.8,42.0,51.0,52.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105135,1
1,2,1,2016-01-01 00:00:00,1339.4,1233.3,1270.9,18.8,42.0,59.0,61.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105136,1
2,3,1,2016-01-01 00:00:00,1317.5,1229.5,1254.9,13.8,41.0,62.0,62.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105137,1
3,4,1,2016-01-01 00:00:00,1277.4,1226.1,1249.0,9.0,41.0,58.0,59.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105138,1
4,5,1,2016-01-01 00:10:00,1429.7,203.9,1154.1,271.7,42.0,51.0,52.0,...,0.24,1.0,0.0,0.0,600.0,99.0,101.0,418.0,105139,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417136,1105130,2,2017-12-31 23:40:00,1269.8,1230.8,1250.2,6.9,38.0,62.0,62.0,...,0.24,1.0,0.0,0.0,600.0,128.0,126.0,425.0,105130,1
417137,1105131,2,2017-12-31 23:50:00,1320.5,1216.8,1262.0,20.6,42.0,56.0,58.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105131,1
417138,1105132,2,2017-12-31 23:50:00,1270.8,1229.6,1249.4,6.6,42.0,56.0,58.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105132,1
417139,1105133,2,2017-12-31 23:50:00,1273.1,1239.8,1250.7,4.7,39.0,59.0,59.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105133,1
417140,1105134,2,2017-12-31 23:50:00,1329.9,1193.0,1257.6,18.9,38.0,61.0,61.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105134,1

In [6]:
datapoint

,datapoint_id,datapoint_mappings_id,datetime,Gen_RPM_Max,Gen_RPM_Min,Gen_RPM_Avg,Gen_RPM_Std,Gen_Bear_Temp_Avg,Gen_Phase1_Temp_Avg,Gen_Phase2_Temp_Avg,...,Anemometer2_Offset,Anemometer2_CorrGain,Anemometer2_CorrOffset,DistanceAirPress,AirRessureSensorZeroOffset,Anemometer1_Avg_Freq,Anemometer2_Avg_Freq,Pressure_Avg_Freq,id,label_categorical_id
0,1,1,2016-01-01 00:00:00,1270.0,1232.8,1248.5,6.8,42.0,51.0,52.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105135,1
1,2,1,2016-01-01 00:00:00,1339.4,1233.3,1270.9,18.8,42.0,59.0,61.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105136,1
2,3,1,2016-01-01 00:00:00,1317.5,1229.5,1254.9,13.8,41.0,62.0,62.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105137,1
3,4,1,2016-01-01 00:00:00,1277.4,1226.1,1249.0,9.0,41.0,58.0,59.0,...,0.24,1.0,0.0,0.0,600.0,98.0,99.0,418.0,105138,1
4,5,1,2016-01-01 00:10:00,1429.7,203.9,1154.1,271.7,42.0,51.0,52.0,...,0.24,1.0,0.0,0.0,600.0,99.0,101.0,418.0,105139,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417136,1105130,2,2017-12-31 23:40:00,1269.8,1230.8,1250.2,6.9,38.0,62.0,62.0,...,0.24,1.0,0.0,0.0,600.0,128.0,126.0,425.0,105130,1
417137,1105131,2,2017-12-31 23:50:00,1320.5,1216.8,1262.0,20.6,42.0,56.0,58.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105131,1
417138,1105132,2,2017-12-31 23:50:00,1270.8,1229.6,1249.4,6.6,42.0,56.0,58.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105132,1
417139,1105133,2,2017-12-31 23:50:00,1273.1,1239.8,1250.7,4.7,39.0,59.0,59.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105133,1
417140,1105134,2,2017-12-31 23:50:00,1329.9,1193.0,1257.6,18.9,38.0,61.0,61.0,...,0.24,1.0,0.0,0.0,600.0,129.0,127.0,425.0,105134,1

In [8]:


datapoint = datapoint.rename(columns={'label_categorical_id': "Risk Level"})

datapoint[datapoint["Risk Level"] == 1] == "low"
datapoint[datapoint["Risk Level"] == 2] == "low-med"
datapoint[datapoint["Risk Level"] == 3] == "medium"
datapoint[datapoint["Risk Level"] == 4] == "med-high"
datapoint[datapoint["Risk Level"] == 5] == "high"

train = datapoint[datapoint["datapoint_mappings_id"]==1]
test = datapoint[datapoint["datapoint_mappings_id"]==2]

train = train.drop(columns={"datapoint_mappings_id", "datetime", "id"})
test = test.drop(columns={"datapoint_mappings_id", "datetime", "id"})

In [16]:
datapoint["datapoint_id"].isna().any()

False